#!/bin/sh                                                                       

wget https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/bird2011dtm.pdf
python -c"import nltk;nltk.download('punkt');nltk.download('averaged_perceptron_tagger');nltk.download('wordnet');nltk.download('stopwords')"
wget -O cloc https://github.com/AlDanial/cloc/releases/download/1.84/cloc-1.84.pl
chmod +x cloc
rm postBuild environment.yml